In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../datasets/ROCK_OR_MINE.csv")

In [3]:
df.head()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
0,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
1,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
2,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
3,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
4,0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,...,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062,R

In [4]:
df["R"].unique()

array(['R', 'M'], dtype=object)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0.0200  207 non-null    float64
 1   0.0371  207 non-null    float64
 2   0.0428  207 non-null    float64
 3   0.0207  207 non-null    float64
 4   0.0954  207 non-null    float64
 5   0.0986  207 non-null    float64
 6   0.1539  207 non-null    float64
 7   0.1601  207 non-null    float64
 8   0.3109  207 non-null    float64
 9   0.2111  207 non-null    float64
 10  0.1609  207 non-null    float64
 11  0.1582  207 non-null    float64
 12  0.2238  207 non-null    float64
 13  0.0645  207 non-null    float64
 14  0.0660  207 non-null    float64
 15  0.2273  207 non-null    float64
 16  0.3100  207 non-null    float64
 17  0.2999  207 non-null    float64
 18  0.5078  207 non-null    float64
 19  0.4797  207 non-null    float64
 20  0.5783  207 non-null    float64
 21  0.5071  207 non-null    float64
 22  0.4328  207 non-null    float64
 23  0.5550  207 non-null    float64
 24  0.6711  207 non-null    float64
 25  0.6415  207 non-null    float64
 26  0.7104  207 non-null    float64
 27  0.8080  207 non-null    float64
 28  0.6791  207 non-null    float64
 29  0.3857  207 non-null    float64
 30  0.1307  207 non-null    float64
 31  0.2604  207 non-null    float64
 32  0.5121  207 non-null    float64
 33  0.7547  207 non-null    float64
 34  0.8537  207 non-null    float64
 35  0.8507  207 non-null    float64
 36  0.6692  207 non-null    float64
 37  0.6097  207 non-null    float64
 38  0.4943  207 non-null    float64
 39  0.2744  207 non-null    float64
 40  0.0510  207 non-null    float64
 41  0.2834  207 non-null    float64
 42  0.2825  207 non-null    float64
 43  0.4256  207 non-null    float64
 44  0.2641  207 non-null    float64
 45  0.1386  207 non-null    float64
 46  0.1051  207 non-null    float64
 47  0.1343  207 non-null    float64
 48  0.0383  207 non-null    float64
 49  0.0324  207 non-null    float64
 50  0.0232  207 non-null    float64
 51  0.0027  207 non-null    float64
 52  0.0065  207 non-null    float64
 53  0.0159  207 non-null    float64
 54  0.0072  207 non-null    float64
 55  0.0167  207 non-null    float64
 56  0.0180  207 non-null    float64
 57  0.0084  207 non-null    float64
 58  0.0090  207 non-null    float64
 59  0.0032  207 non-null    float64
 60  R       207 non-null    object
dtypes: float64(60), object(1)
memory usage: 98.8+ KB

In [6]:
print(df.isnull().values.any())

False

In [7]:
df.head()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
0,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
1,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
2,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
3,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
4,0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,...,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062,R

In [8]:
df["R"] = df["R"].replace({"R": 0, "M": 1})

C:\Users\cathe\AppData\Local\Temp\ipykernel_11984\276411791.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["R"] = df["R"].replace({"R": 0, "M": 1})

In [9]:
df["R"]

0      0
1      0
2      0
3      0
4      0
      ..
202    1
203    1
204    1
205    1
206    1
Name: R, Length: 207, dtype: int64

In [10]:
X = df.drop("R", axis=1)
y = df["R"]

In [11]:
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.3, random_state=42)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
rand_forest_model = RandomForestClassifier()

rand_forest_model.fit(X_train, y_train)
rand_pred = rand_forest_model.predict(X_test)

In [14]:
print(confusion_matrix(y_test, rand_pred))
print("---------------------------------")
print(classification_report(y_test, rand_pred))

[[20  7]
 [ 5 31]]
---------------------------------
              precision    recall  f1-score   support

           0       0.80      0.74      0.77        27
           1       0.82      0.86      0.84        36

    accuracy                           0.81        63
   macro avg       0.81      0.80      0.80        63
weighted avg       0.81      0.81      0.81        63

In [ ]:
print(f"model score on training data: {rand_forest_model.score(X_train, y_train)}")
print(f"model score on testing data: {rand_forest_model.score(X_test, y_test)}")

model score on training data: 1.0
model score on testing data: 0.8095238095238095

In [ ]:
rand_forest_model = RandomForestClassifier()

rand_forest_model.fit(X_train, y_train)
rand_pred = rand_forest_model.predict(X_test)

In [22]:
rand_forest_model_entropy = RandomForestClassifier(criterion="entropy", random_state=42)

rand_forest_model_entropy.fit(X_train, y_train)
rand_pred_entropy = rand_forest_model_entropy.predict(X_test)

print(f"model score on training data: {rand_forest_model_entropy.score(X_train, y_train)}")
print(f"model score on testing data: {rand_forest_model_entropy.score(X_test, y_test)}")
print("---------------------------------")
print(confusion_matrix(y_test, rand_pred_entropy))
print("---------------------------------")
print(classification_report(y_test, rand_pred_entropy))

model score on training data: 1.0
model score on testing data: 0.8412698412698413
---------------------------------
[[21  6]
 [ 4 32]]
---------------------------------
              precision    recall  f1-score   support

           0       0.84      0.78      0.81        27
           1       0.84      0.89      0.86        36

    accuracy                           0.84        63
   macro avg       0.84      0.83      0.84        63
weighted avg       0.84      0.84      0.84        63

In [23]:
rand_forest_model_log = RandomForestClassifier(criterion="log_loss", random_state=42)

rand_forest_model_log.fit(X_train, y_train)
rand_pred_log = rand_forest_model_log.predict(X_test)

print(f"model score on training data: {rand_forest_model_log.score(X_train, y_train)}")
print(f"model score on testing data: {rand_forest_model_log.score(X_test, y_test)}")
print("---------------------------------")
print(confusion_matrix(y_test, rand_pred_log))
print("---------------------------------")
print(classification_report(y_test, rand_pred_log))

model score on training data: 1.0
model score on testing data: 0.8412698412698413
---------------------------------
[[21  6]
 [ 4 32]]
---------------------------------
              precision    recall  f1-score   support

           0       0.84      0.78      0.81        27
           1       0.84      0.89      0.86        36

    accuracy                           0.84        63
   macro avg       0.84      0.83      0.84        63
weighted avg       0.84      0.84      0.84        63